In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('winequality-red2.csv')

In [9]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [10]:
y = df.quality.values
X= df.drop(['quality'], axis=1).values

In [11]:
print y

[5 5 5 ..., 6 5 6]


In [12]:
print X

[[  7.4     0.7     0.    ...,   3.51    0.56    9.4  ]
 [  7.8     0.88    0.    ...,   3.2     0.68    9.8  ]
 [  7.8     0.76    0.04  ...,   3.26    0.65    9.8  ]
 ..., 
 [  6.3     0.51    0.13  ...,   3.42    0.75   11.   ]
 [  5.9     0.645   0.12  ...,   3.57    0.71   10.2  ]
 [  6.      0.31    0.47  ...,   3.39    0.66   11.   ]]


In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
samples_scaled = scaler.transform(X)

In [22]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42 )

In [23]:
import time
start_time = time.time()

from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(64,64,64))

mlp.fit(X_train,y_train)

end_time = time.time()
print("--- %s seconds ---" % ( end_time - start_time))


predictions = mlp.predict(X_test)

end_time2 = time.time()
print("--- %s seconds ---" % ( end_time2 - start_time))

--- 0.578999996185 seconds ---
--- 0.578999996185 seconds ---


In [24]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,predictions))

[[  0   0   0   1   0   0]
 [  0   0   2   8   0   0]
 [  0   0  55  74   1   0]
 [  0   0  25 105   2   0]
 [  0   0   4  37   1   0]
 [  0   0   0   5   0   0]]


In [25]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

          3       0.00      0.00      0.00         1
          4       0.00      0.00      0.00        10
          5       0.64      0.42      0.51       130
          6       0.46      0.80      0.58       132
          7       0.25      0.02      0.04        42
          8       0.00      0.00      0.00         5

avg / total       0.48      0.50      0.45       320

